// Built using NPG-Builder
#ifndef P14-SMALL_INC
#define P14-SMALL_INC

molecule{
  name = "p14-small";

  atom[0] { type = "CB"; position( 1.18645, 0, 0); }
  atom[1] { type = "CB"; position( 1.18645, 1.37, 0); }
  atom[2] { type = "CB"; position( 0, 2.055, 0); }
  atom[3] { type = "CB"; position( 0, 3.425, 0); }
  atom[4] { type = "CB"; position( 3.55936, 0, 0); }
  atom[5] { type = "CB"; position( 3.55936, 1.37, 0); }
  atom[6] { type = "CB"; position( 2.37291, 2.055, 0); }
  atom[7] { type = "CB"; position( 2.37291, 3.425, 0); }
  atom[8] { type = "CB"; position( 5.93227, 0, 0); }
  atom[9] { type = "CB"; position( 5.93227, 1.37, 0); }
  atom[10] { type = "CB"; position( 4.74582, 2.055, 0); }
  atom[11] { type = "CB"; position( 4.74582, 3.425, 0); }
  atom[12] { type = "CB"; position( 8.30518, 0, 0); }
  atom[13] { type = "CB"; position( 8.30518, 1.37, 0); }
  atom[14] { type = "CB"; position( 7.11873, 2.055, 0); }
  atom[15] { type = "CB"; position( 7.11873, 3.425, 0); }
  atom[16] { type = "CB"; position( 10.6781, 0, 0); }
  atom[17] { type = "CB"; position( 10.6781, 1.37, 0); }
  atom[18] { type = "CB"; position( 9.49164, 3.425, 0); }
  atom[19] { type = "CB"; position( 13.051, 0, 0); }
  atom[20] { type = "CB"; position( 13.051, 1.37, 0); }
  atom[21] { type = "CB"; position( 11.8645, 2.055, 0); }
  atom[22] { type = "CB"; position( 11.8645, 3.425, 0); }
  atom[23] { type = "CB"; position( 15.4239, 0, 0); }
  atom[24] { type = "CB"; position( 15.4239, 1.37, 0); }
  atom[25] { type = "CB"; position( 14.2375, 2.055, 0); }
  atom[26] { type = "CB"; position( 14.2375, 3.425, 0); }
  atom[27] { type = "CB"; position( 17.7968, 0, 0); }
  atom[28] { type = "CB"; position( 17.7968, 1.37, 0); }
  atom[29] { type = "CB"; position( 16.6104, 2.055, 0); }
  atom[30] { type = "CB"; position( 16.6104, 3.425, 0); }
  atom[31] { type = "CB"; position( 20.1697, 0, 0); }
  atom[32] { type = "CB"; position( 20.1697, 1.37, 0); }
  atom[33] { type = "CB"; position( 18.9833, 2.055, 0); }
  atom[34] { type = "CB"; position( 18.9833, 3.425, 0); }
  atom[35] { type = "CB"; position( 22.5426, 0, 0); }
  atom[36] { type = "CB"; position( 22.5426, 1.37, 0); }
  atom[37] { type = "CB"; position( 21.3562, 2.055, 0); }
  atom[38] { type = "CB"; position( 21.3562, 3.425, 0); }
  atom[39] { type = "CB"; position( 24.9156, 0, 0); }
  atom[40] { type = "CB"; position( 24.9156, 1.37, 0); }
  atom[41] { type = "CB"; position( 23.7291, 2.055, 0); }
  atom[42] { type = "CB"; position( 23.7291, 3.425, 0); }
  atom[43] { type = "CB"; position( 1.18645, 4.11, 0); }
  atom[44] { type = "CB"; position( 1.18645, 5.48, 0); }
  atom[45] { type = "CB"; position( 0, 6.165, 0); }
  atom[46] { type = "CB"; position( 0, 7.535, 0); }
  atom[47] { type = "CB"; position( 3.55936, 4.11, 0); }
  atom[48] { type = "CB"; position( 3.55936, 5.48, 0); }
  atom[49] { type = "CB"; position( 2.37291, 6.165, 0); }
  atom[50] { type = "CB"; position( 2.37291, 7.535, 0); }
  atom[51] { type = "CB"; position( 5.93227, 4.11, 0); }
  atom[52] { type = "CB"; position( 5.93227, 5.48, 0); }
  atom[53] { type = "CB"; position( 4.74582, 6.165, 0); }
  atom[54] { type = "CB"; position( 4.74582, 7.535, 0); }
  atom[55] { type = "CB"; position( 8.30518, 4.11, 0); }
  atom[56] { type = "CB"; position( 8.30518, 5.48, 0); }
  atom[57] { type = "CB"; position( 7.11873, 6.165, 0); }
  atom[58] { type = "CB"; position( 7.11873, 7.535, 0); }
  atom[59] { type = "CB"; position( 10.6781, 4.11, 0); }
  atom[60] { type = "CB"; position( 10.6781, 5.48, 0); }
  atom[61] { type = "CB"; position( 9.49164, 6.165, 0); }
  atom[62] { type = "CB"; position( 9.49164, 7.535, 0); }
  atom[63] { type = "CB"; position( 13.051, 4.11, 0); }
  atom[64] { type = "CB"; position( 13.051, 5.48, 0); }
  atom[65] { type = "CB"; position( 11.8645, 6.165, 0); }
  atom[66] { type = "CB"; position( 11.8645, 7.535, 0); }
  atom[67] { type = "CB"; position( 15.4239, 4.11, 0); }
  atom[68] { type = "CB"; position( 15.4239, 5.48, 0); }
  atom[69] { type = "CB"; position( 14.2375, 6.165, 0); }
  atom[70] { type = "CB"; position( 14.2375, 7.535, 0); }
  atom[71] { type = "CB"; position( 17.7968, 4.11, 0); }
  atom[72] { type = "CB"; position( 17.7968, 5.48, 0); }
  atom[73] { type = "CB"; position( 16.6104, 6.165, 0); }
  atom[74] { type = "CB"; position( 16.6104, 7.535, 0); }
  atom[75] { type = "CB"; position( 20.1697, 4.11, 0); }
  atom[76] { type = "CB"; position( 20.1697, 5.48, 0); }
  atom[77] { type = "CB"; position( 18.9833, 6.165, 0); }
  atom[78] { type = "CB"; position( 18.9833, 7.535, 0); }
  atom[79] { type = "CB"; position( 22.5426, 4.11, 0); }
  atom[80] { type = "CB"; position( 22.5426, 5.48, 0); }
  atom[81] { type = "CB"; position( 21.3562, 6.165, 0); }
  atom[82] { type = "CB"; position( 21.3562, 7.535, 0); }
  atom[83] { type = "CB"; position( 24.9156, 4.11, 0); }
  atom[84] { type = "CB"; position( 24.9156, 5.48, 0); }
  atom[85] { type = "CB"; position( 23.7291, 6.165, 0); }
  atom[86] { type = "CB"; position( 23.7291, 7.535, 0); }
  atom[87] { type = "CB"; position( 1.18645, 8.22, 0); }
  atom[88] { type = "CB"; position( 1.18645, 9.59, 0); }
  atom[89] { type = "CB"; position( 0, 10.275, 0); }
  atom[90] { type = "CB"; position( 0, 11.645, 0); }
  atom[91] { type = "CB"; position( 3.55936, 8.22, 0); }
  atom[92] { type = "CB"; position( 3.55936, 9.59, 0); }
  atom[93] { type = "CB"; position( 2.37291, 10.275, 0); }
  atom[94] { type = "CB"; position( 2.37291, 11.645, 0); }
  atom[95] { type = "CB"; position( 5.93227, 8.22, 0); }
  atom[96] { type = "CB"; position( 5.93227, 9.59, 0); }
  atom[97] { type = "CB"; position( 4.74582, 10.275, 0); }
  atom[98] { type = "CB"; position( 4.74582, 11.645, 0); }
  atom[99] { type = "CB"; position( 8.30518, 8.22, 0); }
  atom[100] { type = "CB"; position( 8.30518, 9.59, 0); }
  atom[101] { type = "CB"; position( 7.11873, 10.275, 0); }
  atom[102] { type = "CB"; position( 7.11873, 11.645, 0); }
  atom[103] { type = "CB"; position( 10.6781, 8.22, 0); }
  atom[104] { type = "CB"; position( 9.49164, 10.275, 0); }
  atom[105] { type = "CB"; position( 15.4239, 8.22, 0); }
  atom[106] { type = "CB"; position( 17.7968, 8.22, 0); }
  atom[107] { type = "CB"; position( 17.7968, 9.59, 0); }
  atom[108] { type = "CB"; position( 16.6104, 10.275, 0); }
  atom[109] { type = "CB"; position( 20.1697, 8.22, 0); }
  atom[110] { type = "CB"; position( 20.1697, 9.59, 0); }
  atom[111] { type = "CB"; position( 18.9833, 10.275, 0); }
  atom[112] { type = "CB"; position( 18.9833, 11.645, 0); }
  atom[113] { type = "CB"; position( 22.5426, 8.22, 0); }
  atom[114] { type = "CB"; position( 22.5426, 9.59, 0); }
  atom[115] { type = "CB"; position( 21.3562, 10.275, 0); }
  atom[116] { type = "CB"; position( 21.3562, 11.645, 0); }
  atom[117] { type = "CB"; position( 24.9156, 8.22, 0); }
  atom[118] { type = "CB"; position( 24.9156, 9.59, 0); }
  atom[119] { type = "CB"; position( 23.7291, 10.275, 0); }
  atom[120] { type = "CB"; position( 23.7291, 11.645, 0); }
  atom[121] { type = "CB"; position( 1.18645, 12.33, 0); }
  atom[122] { type = "CB"; position( 1.18645, 13.7, 0); }
  atom[123] { type = "CB"; position( 0, 14.385, 0); }
  atom[124] { type = "CB"; position( 0, 15.755, 0); }
  atom[125] { type = "CB"; position( 3.55936, 12.33, 0); }
  atom[126] { type = "CB"; position( 3.55936, 13.7, 0); }
  atom[127] { type = "CB"; position( 2.37291, 14.385, 0); }
  atom[128] { type = "CB"; position( 2.37291, 15.755, 0); }
  atom[129] { type = "CB"; position( 5.93227, 12.33, 0); }
  atom[130] { type = "CB"; position( 5.93227, 13.7, 0); }
  atom[131] { type = "CB"; position( 4.74582, 14.385, 0); }
  atom[132] { type = "CB"; position( 4.74582, 15.755, 0); }
  atom[133] { type = "CB"; position( 8.30518, 13.7, 0); }
  atom[134] { type = "CB"; position( 7.11873, 14.385, 0); }
  atom[135] { type = "CB"; position( 7.11873, 15.755, 0); }
  atom[136] { type = "CB"; position( 9.49164, 15.755, 0); }
  atom[137] { type = "CB"; position( 17.7968, 12.33, 0); }
  atom[138] { type = "CB"; position( 17.7968, 13.7, 0); }
  atom[139] { type = "CB"; position( 16.6104, 15.755, 0); }
  atom[140] { type = "CB"; position( 20.1697, 12.33, 0); }
  atom[141] { type = "CB"; position( 20.1697, 13.7, 0); }
  atom[142] { type = "CB"; position( 18.9833, 14.385, 0); }
  atom[143] { type = "CB"; position( 18.9833, 15.755, 0); }
  atom[144] { type = "CB"; position( 22.5426, 12.33, 0); }
  atom[145] { type = "CB"; position( 22.5426, 13.7, 0); }
  atom[146] { type = "CB"; position( 21.3562, 14.385, 0); }
  atom[147] { type = "CB"; position( 21.3562, 15.755, 0); }
  atom[148] { type = "CB"; position( 24.9156, 12.33, 0); }
  atom[149] { type = "CB"; position( 24.9156, 13.7, 0); }
  atom[150] { type = "CB"; position( 23.7291, 14.385, 0); }
  atom[151] { type = "CB"; position( 23.7291, 15.755, 0); }
  atom[152] { type = "CB"; position( 1.18645, 16.44, 0); }
  atom[153] { type = "CB"; position( 1.18645, 17.81, 0); }
  atom[154] { type = "CB"; position( 0, 18.495, 0); }
  atom[155] { type = "CB"; position( 0, 19.865, 0); }
  atom[156] { type = "CB"; position( 3.55936, 16.44, 0); }
  atom[157] { type = "CB"; position( 3.55936, 17.81, 0); }
  atom[158] { type = "CB"; position( 2.37291, 18.495, 0); }
  atom[159] { type = "CB"; position( 2.37291, 19.865, 0); }
  atom[160] { type = "CB"; position( 5.93227, 16.44, 0); }
  atom[161] { type = "CB"; position( 5.93227, 17.81, 0); }
  atom[162] { type = "CB"; position( 4.74582, 18.495, 0); }
  atom[163] { type = "CB"; position( 4.74582, 19.865, 0); }
  atom[164] { type = "CB"; position( 8.30518, 16.44, 0); }
  atom[165] { type = "CB"; position( 8.30518, 17.81, 0); }
  atom[166] { type = "CB"; position( 7.11873, 18.495, 0); }
  atom[167] { type = "CB"; position( 7.11873, 19.865, 0); }
  atom[168] { type = "CB"; position( 10.6781, 17.81, 0); }
  atom[169] { type = "CB"; position( 9.49164, 18.495, 0); }
  atom[170] { type = "CB"; position( 9.49164, 19.865, 0); }
  atom[171] { type = "CB"; position( 11.8645, 18.495, 0); }
  atom[172] { type = "CB"; position( 11.8645, 19.865, 0); }
  atom[173] { type = "CB"; position( 15.4239, 17.81, 0); }
  atom[174] { type = "CB"; position( 14.2375, 18.495, 0); }
  atom[175] { type = "CB"; position( 14.2375, 19.865, 0); }
  atom[176] { type = "CB"; position( 17.7968, 16.44, 0); }
  atom[177] { type = "CB"; position( 17.7968, 17.81, 0); }
  atom[178] { type = "CB"; position( 16.6104, 18.495, 0); }
  atom[179] { type = "CB"; position( 16.6104, 19.865, 0); }
  atom[180] { type = "CB"; position( 20.1697, 16.44, 0); }
  atom[181] { type = "CB"; position( 20.1697, 17.81, 0); }
  atom[182] { type = "CB"; position( 18.9833, 18.495, 0); }
  atom[183] { type = "CB"; position( 18.9833, 19.865, 0); }
  atom[184] { type = "CB"; position( 22.5426, 16.44, 0); }
  atom[185] { type = "CB"; position( 22.5426, 17.81, 0); }
  atom[186] { type = "CB"; position( 21.3562, 18.495, 0); }
  atom[187] { type = "CB"; position( 21.3562, 19.865, 0); }
  atom[188] { type = "CB"; position( 24.9156, 16.44, 0); }
  atom[189] { type = "CB"; position( 24.9156, 17.81, 0); }
  atom[190] { type = "CB"; position( 23.7291, 18.495, 0); }
  atom[191] { type = "CB"; position( 23.7291, 19.865, 0); }
  atom[192] { type = "CB"; position( 1.18645, 20.55, 0); }
  atom[193] { type = "CB"; position( 1.18645, 21.92, 0); }
  atom[194] { type = "CB"; position( 0, 22.605, 0); }
  atom[195] { type = "CB"; position( 0, 23.975, 0); }
  atom[196] { type = "CB"; position( 3.55936, 20.55, 0); }
  atom[197] { type = "CB"; position( 3.55936, 21.92, 0); }
  atom[198] { type = "CB"; position( 2.37291, 22.605, 0); }
  atom[199] { type = "CB"; position( 2.37291, 23.975, 0); }
  atom[200] { type = "CB"; position( 5.93227, 20.55, 0); }
  atom[201] { type = "CB"; position( 5.93227, 21.92, 0); }
  atom[202] { type = "CB"; position( 4.74582, 22.605, 0); }
  atom[203] { type = "CB"; position( 4.74582, 23.975, 0); }
  atom[204] { type = "CB"; position( 8.30518, 20.55, 0); }
  atom[205] { type = "CB"; position( 8.30518, 21.92, 0); }
  atom[206] { type = "CB"; position( 7.11873, 22.605, 0); }
  atom[207] { type = "CB"; position( 7.11873, 23.975, 0); }
  atom[208] { type = "CB"; position( 10.6781, 20.55, 0); }
  atom[209] { type = "CB"; position( 10.6781, 21.92, 0); }
  atom[210] { type = "CB"; position( 9.49164, 22.605, 0); }
  atom[211] { type = "CB"; position( 9.49164, 23.975, 0); }
  atom[212] { type = "CB"; position( 13.051, 20.55, 0); }
  atom[213] { type = "CB"; position( 13.051, 21.92, 0); }
  atom[214] { type = "CB"; position( 11.8645, 22.605, 0); }
  atom[215] { type = "CB"; position( 11.8645, 23.975, 0); }
  atom[216] { type = "CB"; position( 15.4239, 20.55, 0); }
  atom[217] { type = "CB"; position( 15.4239, 21.92, 0); }
  atom[218] { type = "CB"; position( 14.2375, 22.605, 0); }
  atom[219] { type = "CB"; position( 14.2375, 23.975, 0); }
  atom[220] { type = "CB"; position( 17.7968, 20.55, 0); }
  atom[221] { type = "CB"; position( 17.7968, 21.92, 0); }
  atom[222] { type = "CB"; position( 16.6104, 22.605, 0); }
  atom[223] { type = "CB"; position( 16.6104, 23.975, 0); }
  atom[224] { type = "CB"; position( 20.1697, 20.55, 0); }
  atom[225] { type = "CB"; position( 20.1697, 21.92, 0); }
  atom[226] { type = "CB"; position( 18.9833, 22.605, 0); }
  atom[227] { type = "CB"; position( 18.9833, 23.975, 0); }
  atom[228] { type = "CB"; position( 22.5426, 20.55, 0); }
  atom[229] { type = "CB"; position( 22.5426, 21.92, 0); }
  atom[230] { type = "CB"; position( 21.3562, 22.605, 0); }
  atom[231] { type = "CB"; position( 21.3562, 23.975, 0); }
  atom[232] { type = "CB"; position( 24.9156, 20.55, 0); }
  atom[233] { type = "CB"; position( 24.9156, 21.92, 0); }
  atom[234] { type = "CB"; position( 23.7291, 22.605, 0); }
  atom[235] { type = "CB"; position( 23.7291, 23.975, 0); }
  atom[236] { type = "CA"; position( 13.051, 8.22, 0); }
  atom[237] { type = "CA"; position( 15.4239, 9.59, 0); }
  atom[238] { type = "CA"; position( 16.6104, 11.645, 0); }
  atom[239] { type = "CA"; position( 16.6104, 14.385, 0); }
  atom[240] { type = "CA"; position( 15.4239, 16.44, 0); }
  atom[241] { type = "CA"; position( 13.051, 17.81, 0); }
  atom[242] { type = "CA"; position( 10.6781, 16.44, 0); }
  atom[243] { type = "CA"; position( 9.49164, 14.385, 0); }
  atom[244] { type = "CB"; position( 8.30518, 12.33, 0); }
  atom[245] { type = "CA"; position( 9.49164, 11.645, 0); }
  atom[246] { type = "CA"; position( 10.6781, 9.59, 0); }
  atom[247] { type = "HA"; position( 11.8645, 15.755, 0); }
  atom[248] { type = "HA"; position( 13.051, 16.44, 0); }
  atom[249] { type = "HA"; position( 14.2375, 15.755, 0); }
  atom[250] { type = "HA"; position( 15.4239, 13.7, 0); }
  atom[251] { type = "HA"; position( 15.4239, 12.33, 0); }
  atom[252] { type = "HA"; position( 14.2375, 10.275, 0); }
  atom[253] { type = "HA"; position( 13.051, 9.59, 0); }
  atom[254] { type = "HA"; position( 11.8645, 10.275, 0); }
  atom[255] { type = "HA"; position( 10.6781, 12.33, 0); }
  atom[256] { type = "HA"; position( 10.6781, 13.7, 0); }
  atom[257] { type = "CB"; position( 9.49164, 2.055, 0); }

  // This list includes bonds_ that span the box
  bond { members(0, 1); }
  bond { members(1, 2); }
  bond { members(1, 6); }
  bond { members(2, 3); }
  bond { members(3, 43); }
  bond { members(4, 5); }
  bond { members(5, 6); }
  bond { members(5, 10); }
  bond { members(6, 7); }
  bond { members(7, 43); }
  bond { members(7, 47); }
  bond { members(8, 9); }
  bond { members(9, 10); }
  bond { members(9, 14); }
  bond { members(10, 11); }
  bond { members(11, 47); }
  bond { members(11, 51); }
  bond { members(12, 13); }
  bond { members(13, 14); }
  bond { members(13, 257); }
  bond { members(14, 15); }
  bond { members(15, 51); }
  bond { members(15, 55); }
  bond { members(16, 17); }
  bond { members(17, 21); }
  bond { members(17, 257); }
  bond { members(18, 55); }
  bond { members(18, 59); }
  bond { members(19, 20); }
  bond { members(20, 21); }
  bond { members(20, 25); }
  bond { members(21, 22); }
  bond { members(22, 59); }
  bond { members(22, 63); }
  bond { members(23, 24); }
  bond { members(24, 25); }
  bond { members(24, 29); }
  bond { members(25, 26); }
  bond { members(26, 63); }
  bond { members(26, 67); }
  bond { members(27, 28); }
  bond { members(28, 29); }
  bond { members(28, 33); }
  bond { members(29, 30); }
  bond { members(30, 67); }
  bond { members(30, 71); }
  bond { members(31, 32); }
  bond { members(32, 33); }
  bond { members(32, 37); }
  bond { members(33, 34); }
  bond { members(34, 71); }
  bond { members(34, 75); }
  bond { members(35, 36); }
  bond { members(36, 37); }
  bond { members(36, 41); }
  bond { members(37, 38); }
  bond { members(38, 75); }
  bond { members(38, 79); }
  bond { members(39, 40); }
  bond { members(40, 41); }
  bond { members(41, 42); }
  bond { members(42, 79); }
  bond { members(42, 83); }
  bond { members(43, 44); }
  bond { members(44, 45); }
  bond { members(44, 49); }
  bond { members(45, 46); }
  bond { members(46, 87); }
  bond { members(47, 48); }
  bond { members(48, 49); }
  bond { members(48, 53); }
  bond { members(49, 50); }
  bond { members(50, 87); }
  bond { members(50, 91); }
  bond { members(51, 52); }
  bond { members(52, 53); }
  bond { members(52, 57); }
  bond { members(53, 54); }
  bond { members(54, 91); }
  bond { members(54, 95); }
  bond { members(55, 56); }
  bond { members(56, 57); }
  bond { members(56, 61); }
  bond { members(57, 58); }
  bond { members(58, 95); }
  bond { members(58, 99); }
  bond { members(59, 60); }
  bond { members(60, 61); }
  bond { members(60, 65); }
  bond { members(61, 62); }
  bond { members(62, 99); }
  bond { members(62, 103); }
  bond { members(63, 64); }
  bond { members(64, 65); }
  bond { members(64, 69); }
  bond { members(65, 66); }
  bond { members(66, 103); }
  bond { members(66, 236); }
  bond { members(67, 68); }
  bond { members(68, 69); }
  bond { members(68, 73); }
  bond { members(69, 70); }
  bond { members(70, 105); }
  bond { members(70, 236); }
  bond { members(71, 72); }
  bond { members(72, 73); }
  bond { members(72, 77); }
  bond { members(73, 74); }
  bond { members(74, 105); }
  bond { members(74, 106); }
  bond { members(75, 76); }
  bond { members(76, 77); }
  bond { members(76, 81); }
  bond { members(77, 78); }
  bond { members(78, 106); }
  bond { members(78, 109); }
  bond { members(79, 80); }
  bond { members(80, 81); }
  bond { members(80, 85); }
  bond { members(81, 82); }
  bond { members(82, 109); }
  bond { members(82, 113); }
  bond { members(83, 84); }
  bond { members(84, 85); }
  bond { members(85, 86); }
  bond { members(86, 113); }
  bond { members(86, 117); }
  bond { members(87, 88); }
  bond { members(88, 89); }
  bond { members(88, 93); }
  bond { members(89, 90); }
  bond { members(90, 121); }
  bond { members(91, 92); }
  bond { members(92, 93); }
  bond { members(92, 97); }
  bond { members(93, 94); }
  bond { members(94, 121); }
  bond { members(94, 125); }
  bond { members(95, 96); }
  bond { members(96, 97); }
  bond { members(96, 101); }
  bond { members(97, 98); }
  bond { members(98, 125); }
  bond { members(98, 129); }
  bond { members(99, 100); }
  bond { members(100, 101); }
  bond { members(100, 104); }
  bond { members(101, 102); }
  bond { members(102, 129); }
  bond { members(102, 244); }
  bond { members(103, 246); }
  bond { members(104, 245); }
  bond { members(105, 237); }
  bond { members(106, 107); }
  bond { members(107, 108); }
  bond { members(107, 111); }
  bond { members(108, 238); }
  bond { members(109, 110); }
  bond { members(110, 111); }
  bond { members(110, 115); }
  bond { members(111, 112); }
  bond { members(112, 137); }
  bond { members(112, 140); }
  bond { members(113, 114); }
  bond { members(114, 115); }
  bond { members(114, 119); }
  bond { members(115, 116); }
  bond { members(116, 140); }
  bond { members(116, 144); }
  bond { members(117, 118); }
  bond { members(118, 119); }
  bond { members(119, 120); }
  bond { members(120, 144); }
  bond { members(120, 148); }
  bond { members(121, 122); }
  bond { members(122, 123); }
  bond { members(122, 127); }
  bond { members(123, 124); }
  bond { members(124, 152); }
  bond { members(125, 126); }
  bond { members(126, 127); }
  bond { members(126, 131); }
  bond { members(127, 128); }
  bond { members(128, 152); }
  bond { members(128, 156); }
  bond { members(129, 130); }
  bond { members(130, 131); }
  bond { members(130, 134); }
  bond { members(131, 132); }
  bond { members(132, 156); }
  bond { members(132, 160); }
  bond { members(133, 134); }
  bond { members(133, 243); }
  bond { members(134, 135); }
  bond { members(135, 160); }
  bond { members(135, 164); }
  bond { members(136, 164); }
  bond { members(136, 242); }
  bond { members(137, 138); }
  bond { members(138, 142); }
  bond { members(138, 239); }
  bond { members(139, 176); }
  bond { members(139, 240); }
  bond { members(140, 141); }
  bond { members(141, 142); }
  bond { members(141, 146); }
  bond { members(142, 143); }
  bond { members(143, 176); }
  bond { members(143, 180); }
  bond { members(144, 145); }
  bond { members(145, 146); }
  bond { members(145, 150); }
  bond { members(146, 147); }
  bond { members(147, 180); }
  bond { members(147, 184); }
  bond { members(148, 149); }
  bond { members(149, 150); }
  bond { members(150, 151); }
  bond { members(151, 184); }
  bond { members(151, 188); }
  bond { members(152, 153); }
  bond { members(153, 154); }
  bond { members(153, 158); }
  bond { members(154, 155); }
  bond { members(155, 192); }
  bond { members(156, 157); }
  bond { members(157, 158); }
  bond { members(157, 162); }
  bond { members(158, 159); }
  bond { members(159, 192); }
  bond { members(159, 196); }
  bond { members(160, 161); }
  bond { members(161, 162); }
  bond { members(161, 166); }
  bond { members(162, 163); }
  bond { members(163, 196); }
  bond { members(163, 200); }
  bond { members(164, 165); }
  bond { members(165, 166); }
  bond { members(165, 169); }
  bond { members(166, 167); }
  bond { members(167, 200); }
  bond { members(167, 204); }
  bond { members(168, 169); }
  bond { members(168, 171); }
  bond { members(169, 170); }
  bond { members(170, 204); }
  bond { members(170, 208); }
  bond { members(171, 172); }
  bond { members(172, 208); }
  bond { members(172, 212); }
  bond { members(173, 174); }
  bond { members(173, 178); }
  bond { members(174, 175); }
  bond { members(175, 212); }
  bond { members(175, 216); }
  bond { members(176, 177); }
  bond { members(177, 178); }
  bond { members(177, 182); }
  bond { members(178, 179); }
  bond { members(179, 216); }
  bond { members(179, 220); }
  bond { members(180, 181); }
  bond { members(181, 182); }
  bond { members(181, 186); }
  bond { members(182, 183); }
  bond { members(183, 220); }
  bond { members(183, 224); }
  bond { members(184, 185); }
  bond { members(185, 186); }
  bond { members(185, 190); }
  bond { members(186, 187); }
  bond { members(187, 224); }
  bond { members(187, 228); }
  bond { members(188, 189); }
  bond { members(189, 190); }
  bond { members(190, 191); }
  bond { members(191, 228); }
  bond { members(191, 232); }
  bond { members(192, 193); }
  bond { members(193, 194); }
  bond { members(193, 198); }
  bond { members(194, 195); }
  bond { members(196, 197); }
  bond { members(197, 198); }
  bond { members(197, 202); }
  bond { members(198, 199); }
  bond { members(200, 201); }
  bond { members(201, 202); }
  bond { members(201, 206); }
  bond { members(202, 203); }
  bond { members(204, 205); }
  bond { members(205, 206); }
  bond { members(205, 210); }
  bond { members(206, 207); }
  bond { members(208, 209); }
  bond { members(209, 210); }
  bond { members(209, 214); }
  bond { members(210, 211); }
  bond { members(212, 213); }
  bond { members(213, 214); }
  bond { members(213, 218); }
  bond { members(214, 215); }
  bond { members(216, 217); }
  bond { members(217, 218); }
  bond { members(217, 222); }
  bond { members(218, 219); }
  bond { members(220, 221); }
  bond { members(221, 222); }
  bond { members(221, 226); }
  bond { members(222, 223); }
  bond { members(224, 225); }
  bond { members(225, 226); }
  bond { members(225, 230); }
  bond { members(226, 227); }
  bond { members(228, 229); }
  bond { members(229, 230); }
  bond { members(229, 234); }
  bond { members(230, 231); }
  bond { members(232, 233); }
  bond { members(233, 234); }
  bond { members(234, 235); }
  bond { members(237, 108); }
  bond { members(238, 137); }
  bond { members(239, 139); }
  bond { members(240, 173); }
  bond { members(241, 171); }
  bond { members(241, 174); }
  bond { members(242, 168); }
  bond { members(243, 136); }
  bond { members(244, 133); }
  bond { members(245, 244); }
  bond { members(246, 104); }
  bond { members(247, 242); }
  bond { members(248, 241); }
  bond { members(249, 240); }
  bond { members(250, 239); }
  bond { members(251, 238); }
  bond { members(252, 237); }
  bond { members(253, 236); }
  bond { members(254, 246); }
  bond { members(255, 245); }
  bond { members(256, 243); }
  bond { members(257, 18); }
  bond { members(39, 195); }
  bond { members(40, 2); }
  bond { members(83, 3); }
  bond { members(84, 45); }
  bond { members(117, 46); }
  bond { members(118, 89); }
  bond { members(148, 90); }
  bond { members(149, 123); }
  bond { members(188, 124); }
  bond { members(189, 154); }
  bond { members(195, 0); }
  bond { members(199, 0); }
  bond { members(199, 4); }
  bond { members(203, 4); }
  bond { members(203, 8); }
  bond { members(207, 8); }
  bond { members(207, 12); }
  bond { members(211, 12); }
  bond { members(211, 16); }
  bond { members(215, 16); }
  bond { members(215, 19); }
  bond { members(219, 19); }
  bond { members(219, 23); }
  bond { members(223, 23); }
  bond { members(223, 27); }
  bond { members(227, 27); }
  bond { members(227, 31); }
  bond { members(231, 31); }
  bond { members(231, 35); }
  bond { members(232, 155); }
  bond { members(233, 194); }
  bond { members(235, 35); }
  bond { members(235, 39); }
}

#endif
