#!/bin/bash
module load vasp/5.4.1[cdrisko@crcfe01:vasp]$.

cd /afs/crc.nd.edu/user/c/cdrisko/ND-Coursework/Comp_Chem/VASP/Metals
cd /afs/crc.nd.edu/user/c/cdrisko/ND-Coursework/Comp_Chem/VASP/Metals/Au/O-on-Au-fcc-ados  # this is the vasp directory

runvasp.py     # this is the vasp command
#end
